User renderer
Group renderer
PidFile /var/run/renderd/httpd.pid

ServerName localhost
UseCanonicalName On
Listen 8080
<VirtualHost *:8080>
    ServerAdmin admin@localhost

    LoadTileConfigFile /usr/local/etc/renderd.conf
    ModTileTileDir /var/cache/renderd/tiles
    ModTileEnableStats On
    # ModTileBulkMode Off
    ModTileRequestTimeout 0
    ModTileMissingRequestTimeout 30
    ModTileMaxLoadOld 16
    ModTileMaxLoadMissing 50
    # ModTileVeryOldThreshold 31536000000000
    ModTileRenderdSocketName /var/run/renderd/renderd.sock
    # ModTileCacheDurationMax 604800
    # ModTileCacheDurationDirty 900
    # ModTileCacheDurationMinimum 10800
    # ModTileCacheDurationMediumZoom 13 86400
    # ModTileCacheDurationLowZoom 9 518400
    # ModTileCacheLastModifiedFactor 0.20
    # ModTileEnableTileThrottling Off
    # ModTileEnableTileThrottlingXForward 0
    # ModTileThrottlingTiles 10000 1
    # ModTileThrottlingRenders 128 0.2

    LogLevel warn

    DocumentRoot /var/www/html

    <Directory "/var/www/html">
        Options -Indexes +FollowSymLinks
        AllowOverride None
        Require all granted
    </Directory>

    ErrorLogFormat "%{%Y-%m-%dT%H:%M:%S.%Q%z}t [%l] %M"
    ErrorLog /var/log/httpd/error.log
    LogFormat "%{%Y-%m-%dT%H:%M:%S%z}t [INFO] %h \"%r\" %>s %b" custom
    CustomLog /var/log/httpd/access.log custom

    Alias "/renderd_stats" "/var/run/renderd/renderd.stats"
    <Location "/renderd_stats">
        Require all granted
        ForceType text/plain
        Header set Content-Type "text/plain; charset=utf-8"
    </Location>
</VirtualHost>
